[versions]
kotlin-logging = "7.0.13"
kotlin-math = "1.7.0"
kotlinx-browser = "0.5.0"
kotlinx-io = "0.8.2"
vulkan-kotlin = "1.4.328-4"

[libraries]
kotlin-logging = { module = "io.github.oshai:kotlin-logging", version.ref = "kotlin-logging" }
kotlin-math = { module = "io.technoirlab:kotlin-math", version.ref = "kotlin-math" }
kotlinx-browser = { module = "org.jetbrains.kotlinx:kotlinx-browser", version.ref = "kotlinx-browser" }
kotlinx-io-core = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "kotlinx-io" }
vulkan-kotlin = { module = "io.technoirlab.vulkan:vulkan-kotlin", version.ref = "vulkan-kotlin" }
