name: Deploy

on:
  push:
    tags: [ "*" ]

concurrency:
  group: ${{ github.workflow }}

jobs:
  packages:
    name: Packages
    runs-on: macos-26

    permissions:
      contents: write # Required for creating release
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: Set up JDK
        uses: actions/setup-java@v5.1.0
        with:
          java-version: 21
          distribution: corretto

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5.0.0

      - name: Cache Kotlin/Native toolchains
        uses: actions/cache@v5.0.2
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('settings.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-konan-

      - name: Publish to GitHub Packages
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        run: |
          ./gradlew publishAllPublicationsToGithubRepository \
          --scan \
          -Ppublish.github.username=${{ secrets.GPR_DEPLOY_USER }} \
          -Ppublish.github.password=${{ secrets.GPR_DEPLOY_TOKEN }}

      - name: Create release
        uses: softprops/action-gh-release@v2.5.0
        if: github.ref_type == 'tag'
        with:
          generate_release_notes: true

  documentation:
    name: Documentation
    runs-on: macos-26

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: Set up JDK
        uses: actions/setup-java@v5.1.0
        with:
          java-version: 21
          distribution: corretto

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5.0.0

      - name: Setup Pages
        uses: actions/configure-pages@v5.0.0

      - name: Cache Kotlin/Native toolchains
        uses: actions/cache@v5.0.2
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('settings.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-konan-

      - name: Generate documentation
        run: ./gradlew :dokkaGenerate --scan

      - name: Upload documentation
        uses: actions/upload-pages-artifact@v4.0.0
        with:
          path: build/dokka/html

      - name: Deploy documentation to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
